-- Ejecutar exclusivamente en una BD PostgreSQL de laboratorio vacía/autorizada.
CREATE TYPE ubicacion AS (ciudad TEXT, provincia TEXT);
CREATE TABLE club_obj (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  sede ubicacion NOT NULL
);
INSERT INTO club_obj(nombre, sede)
VALUES ('Granada CF', ROW('Granada', 'Granada')::ubicacion);
SELECT id, nombre, (sede).ciudad, (sede).provincia FROM club_obj;
UPDATE club_obj SET sede = ROW('Motril', 'Granada')::ubicacion
WHERE nombre = 'Granada CF';
